version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /home/brunolaier/Documentos/Projetos/orbita-challenge-full-stack-web/database:/var/lib/postgresql/data 
